argocd-apps:
  applications:
    traefik-ingress:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/traefik
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: traefik-ingress
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    argocd:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/argocd
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    external-secrets:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/external-secrets/deploy
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

    vault:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/vault/server
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: vault
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    cloudnative-pg:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/cloudnative-pg
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: cloudnative-pg
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

    cloudflared:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/cloudflared/chart
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: cloudflared
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    external-dns:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/external-dns
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: external-dns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    cert-manager:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/cert-manager
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    cilium:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/cilium
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

    hetzner-cloud-controller:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/hetzner-cloud-controller
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    karpenter:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/karpenter
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: karpenter
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    renovate:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/renovate
        targetRevision: main
        helm:
          parameters:
            - name: gitRevision
              value: $ARGOCD_APP_REVISION
      destination:
        server: https://kubernetes.default.svc
        namespace: renovate
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    sysbox:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/sysbox/deploy
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    monitoring:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/services/monitoring
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    github-arc-runners-controller:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/github-arc-runners/controller
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: arc-systems
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    github-arc-runners-generator:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/github-arc-runners/runners-generator
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    system-upgrade-controller:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/kubernetes/upgrades/system-upgrade-controller
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: system-upgrade
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    k3s-upgrades:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/kubernetes/upgrades/plans
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: system-upgrade
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    documentation:
      project: default
      sources:
        - repoURL: https://github.com/kbntx-org/nexus.git
          path: docs/helm
          targetRevision: main
          helm:
            valueFiles:
              - values.yaml
              - $values/documentation/values.yaml
        - repoURL: https://github.com/kbntx-org/nexus-manifests.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: documentation
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    cloudflare-controller:
      project: default
      sources:
        - repoURL: https://github.com/kbntx-org/nexus.git
          path: platform/core/cloudflare-controller/chart
          targetRevision: main
          helm:
            valueFiles:
              - values.yaml
              - $values/cloudflare-controller/values.yaml
        - repoURL: https://github.com/kbntx-org/nexus-manifests.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: cloudflare-controller
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    n8n:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/services/n8n
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: n8n
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    portfolio:
      project: default
      sources:
        - repoURL: https://github.com/kbntx-org/nexus.git
          path: apps/portfolio/chart
          targetRevision: main
          helm:
            valueFiles:
              - values.yaml
              - $values/portfolio/values.yaml
        - repoURL: https://github.com/kbntx-org/nexus-manifests.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: portfolio
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    kiln:
      project: default
      sources:
        - repoURL: https://github.com/kbntx-org/nexus.git
          path: platform/services/kiln/chart
          targetRevision: main
          helm:
            valueFiles:
              - values.yaml
              - $values/kiln/values.yaml
        - repoURL: https://github.com/kbntx-org/nexus-manifests.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: kiln
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

    smelt:
      project: default
      sources:
        - repoURL: https://github.com/kbntx-org/smelt.git
          path: chart
          targetRevision: main
          helm:
            valueFiles:
              - values.yaml
        - repoURL: https://github.com/kbntx-org/nexus-manifests.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: smelt
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
