apiVersion: v2
name: monitoring-stack
version: 1.0.0
dependencies:
  - name: grafana
    version: 12.11.2
    repository: https://grafana-community.github.io/helm-charts
  - name: loki
    version: 7.3.0
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.17.1
    repository: https://grafana.github.io/helm-charts
  - name: kube-state-metrics
    version: 8.4.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-node-exporter
    version: 4.56.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: victoria-metrics-single
    version: 0.45.0
    repository: https://victoriametrics.github.io/helm-charts
