apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate-secret-sa
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: renovate-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: renovate-secret-sa
            audiences:
              - vault
      path: platform
      server: https://vault.kbntx.com
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: renovate-secret-store
    kind: SecretStore
  target:
    name: renovate-secrets
  dataFrom:
    - extract:
        key: renovate
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-userdata
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: renovate-secret-store
    kind: SecretStore
  target:
    name: renovate-userdata
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        userData: |
          #cloud-config
          write_files:
            - path: /etc/rancher/k3s/config.yaml.tmpl
              owner: root:root
              permissions: '0600'
              content: |
                token: {{ `{{ .agentToken }}` }}
                node-name: ${NODE_NAME}
                node-ip: ${NODE_IP}
                server: "https://{{ .Values.karpenter.userData.k3sServerURL }}:6443"
                kubelet-arg:
                  - "cloud-provider=external"
          runcmd:
            - |
              export NODE_NAME="$(hostname)"
              export NODE_IP="$(ip -4 addr show enp7s0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')"
              envsubst < /etc/rancher/k3s/config.yaml.tmpl > /etc/rancher/k3s/config.yaml
            - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ .Values.karpenter.userData.k3sVersion }} sh -s - agent
  dataFrom:
    - extract:
        key: renovate
